-- Tabulky

CREATE TABLE  "Bet"
(
	"ID" NUMBER(8) NOT NULL,
	"DESCRIPTION" VARCHAR2(255) NOT NULL,
	"START_DATE" DATE NOT NULL,
	"END_DATE" DATE NOT NULL,
	"MATCH_ID" NUMBER(8) NOT NULL,
	"RATE" NUMBER(8, 2) NOT NULL
)
;

CREATE TABLE  "Match"
(
	"ID" NUMBER(8) NOT NULL,
	"TEAM1" NUMBER(8) NOT NULL,
	"TEAM2" NUMBER(8) NOT NULL,
	"PLAYED_AT" DATE NOT NULL,
	"DESCRIPTION" VARCHAR2(255) NOT NULL,
	"RESULT" VARCHAR2(10) NOT NULL
)
;

CREATE TABLE  "Team"
(
	"ID" NUMBER(8) NOT NULL,
	"NAME" VARCHAR2(50) NOT NULL,
	"WINS" NUMBER(8) NOT NULL,
	"LOSSES" NUMBER(8) NOT NULL,
	"RATING" NUMBER(10, 2) NOT NULL
)
;

CREATE TABLE  "User"
(
	"ID" NUMBER(8) NOT NULL,
	"FIRST_NAME" VARCHAR2(255) NOT NULL,
	"LAST_NAME" VARCHAR2(255) NOT NULL,
	"EMAIL" VARCHAR2(255) NOT NULL UNIQUE,
	"PASSWORD" VARCHAR2(255) NOT NULL,
	"BIRTHDATE" DATE NOT NULL,
	"ADMIN" CHAR(1 BYTE) NOT NULL
)
;

CREATE TABLE  "UserAccount"
(
	"ID" NUMBER(8) NOT NULL,
	"AMOUNT" NUMBER(8,2) NOT NULL,
	"DESCRIPTION" VARCHAR2(255) NULL,
	"USER_ID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "UserBet"
(
	"ID" NUMBER(8) NOT NULL,
	"BET_AMOUNT" NUMBER(8,2) NOT NULL,
	"CREATED_AT" DATE NOT NULL,
	"USER_ID" NUMBER(8) NOT NULL,
	"BET_ID" NUMBER(8) NOT NULL
)
;

-- Sekvence, Triggery

CREATE SEQUENCE "SEQ_Bet_ID"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE  1
	NOCYCLE
	NOCACHE
	NOORDER
;

CREATE OR REPLACE TRIGGER "TRG_Bet_ID"
	BEFORE INSERT
	ON "Bet"
	FOR EACH ROW
	BEGIN
		SELECT "SEQ_Bet_ID".NEXTVAL
		INTO :NEW."ID"
		FROM DUAL;
	END
;
/


CREATE SEQUENCE "SEQ_Match_ID"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE  1
	NOCYCLE
	NOCACHE
	NOORDER
;

CREATE OR REPLACE TRIGGER "TRG_Match_ID"
	BEFORE INSERT
	ON "Match"
	FOR EACH ROW
	BEGIN
		SELECT "SEQ_Match_ID".NEXTVAL
		INTO :NEW."ID"
		FROM DUAL;
	END
;
/

CREATE SEQUENCE "SEQ_Team_ID"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE  1
	NOCYCLE
	NOCACHE
	NOORDER
;

CREATE OR REPLACE TRIGGER "TRG_Team_ID"
	BEFORE INSERT
	ON "Team"
	FOR EACH ROW
	BEGIN
		SELECT "SEQ_Team_ID".NEXTVAL
		INTO :NEW."ID"
		FROM DUAL;
	END
;
/

CREATE SEQUENCE "SEQ_User_ID"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE  1
	NOCYCLE
	NOCACHE
	NOORDER
;

CREATE OR REPLACE TRIGGER "TRG_User_ID"
	BEFORE INSERT
	ON "User"
	FOR EACH ROW
	BEGIN
		SELECT "SEQ_User_ID".NEXTVAL
		INTO :NEW."ID"
		FROM DUAL;
	END
;
/


CREATE SEQUENCE "SEQ_UserAccount_ID"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE  1
	NOCYCLE
	NOCACHE
	NOORDER
;

CREATE OR REPLACE TRIGGER "TRG_UserAccount_ID"
	BEFORE INSERT
	ON "UserAccount"
	FOR EACH ROW
	BEGIN
		SELECT "SEQ_UserAccount_ID".NEXTVAL
		INTO :NEW."ID"
		FROM DUAL;
	END
;
/


CREATE SEQUENCE "SEQ_UserBet_ID"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE  1
	NOCYCLE
	NOCACHE
	NOORDER
;

CREATE OR REPLACE TRIGGER "TRG_UserBet_ID"
	BEFORE INSERT
	ON "UserBet"
	FOR EACH ROW
	BEGIN
		SELECT "SEQ_UserBet_ID".NEXTVAL
		INTO :NEW."ID"
		FROM DUAL;
	END
;
/

-- Primární klíče, indexy

ALTER TABLE  "Bet"
 ADD CONSTRAINT "PK_Bet"
	PRIMARY KEY ("ID")
 USING INDEX
;

ALTER TABLE  "Match"
 ADD CONSTRAINT "PK_Match"
	PRIMARY KEY ("ID")
 USING INDEX
;

ALTER TABLE  "Team"
 ADD CONSTRAINT "PK_Team"
	PRIMARY KEY ("ID")
 USING INDEX
;

ALTER TABLE  "User"
 ADD CONSTRAINT "PK_User"
	PRIMARY KEY ("ID")
 USING INDEX
;

ALTER TABLE  "UserAccount"
 ADD CONSTRAINT "PK_UserAccount"
	PRIMARY KEY ("ID")
 USING INDEX
;

ALTER TABLE  "UserBet"
 ADD CONSTRAINT "PK_UserBet"
	PRIMARY KEY ("ID")
 USING INDEX
;

-- Cizí klíče

ALTER TABLE  "Bet"
 ADD CONSTRAINT "FK_Bet_Match"
	FOREIGN KEY ("MATCH_ID") REFERENCES  "Match" ("ID")
;

ALTER TABLE  "Match"
 ADD CONSTRAINT "FK_Match_Team"
	FOREIGN KEY ("TEAM1") REFERENCES  "Team" ("ID")
;

ALTER TABLE  "Match"
 ADD CONSTRAINT "FK_Match_Team02"
	FOREIGN KEY ("TEAM2") REFERENCES  "Team" ("ID")
;

ALTER TABLE  "UserAccount"
 ADD CONSTRAINT "FK_UserAccount_User"
	FOREIGN KEY ("USER_ID") REFERENCES  "User" ("ID")
;

ALTER TABLE  "UserBet"
 ADD CONSTRAINT "FK_UserBet_Bet"
	FOREIGN KEY ("BET_ID") REFERENCES  "Bet" ("ID")
;

ALTER TABLE  "UserBet"
 ADD CONSTRAINT "FK_UserBet_User"
	FOREIGN KEY ("USER_ID") REFERENCES  "User" ("ID")
;