DROP TABLE "DW_MATCH" CASCADE CONSTRAINTS;
DROP TABLE "DW_USER" CASCADE CONSTRAINTS;
DROP TABLE "DW_USER_BET" CASCADE CONSTRAINTS;
DROP TABLE "DW_USER_BET_DETAIL" CASCADE CONSTRAINTS;

-- Vytvoreni tabulek
CREATE TABLE DW_MATCH (
    ID INTEGER NOT NULL,
    TEAM1_NAME VARCHAR(255) NOT NULL,
    TEAM2_NAME VARCHAR(255) NOT NULL,
    PLAYED_AT DATE NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    RESULT VARCHAR(10) NOT NULL
);

CREATE TABLE DW_USER (
    ID INTEGER NOT NULL, -- PK_ds_klient
    FIRST_NAME VARCHAR (255) NOT NULL,
    LAST_NAME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    PASSWORD VARCHAR (255) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    ADMIN CHAR(1 BYTE) NOT NULL
);

CREATE TABLE DW_USER_BET (
    ID INTEGER NOT NULL, -- PK_ds_transakce
    BET_AMOUNT NUMBER(8,2) NOT NULL,
    CREATED_AT DATE NOT NULL,
    RATE NUMBER NOT NULL
);

CREATE TABLE DW_USER_BET_DETAIL (
    MATCH_ID INTEGER NOT NULL, -- FK_ds_banker (ds_banker --> id_banker)
    USER_ID INTEGER NOT NULL, -- FK_ds_klient (ds_klient --> id_klient)
    USER_BET_ID INTEGER NOT NULL -- FK_ds_transakce (ds_transakce --> id_transakce)
);

-- Pridani primarnich klicu
ALTER TABLE DW_MATCH ADD CONSTRAINT PK_DW_MATCH PRIMARY KEY(ID);
ALTER TABLE DW_USER ADD CONSTRAINT PK_DW_USER PRIMARY KEY(ID);
ALTER TABLE DW_USER_BET ADD CONSTRAINT PK_DW_USER_BET PRIMARY KEY(ID);

-- Pridani cizich klicu
ALTER TABLE DW_USER_BET_DETAIL ADD CONSTRAINT FK_DW_MATCH FOREIGN KEY(MATCH_ID) REFERENCES DW_MATCH(ID);
ALTER TABLE DW_USER_BET_DETAIL ADD CONSTRAINT FK_DW_USER FOREIGN KEY(USER_ID) REFERENCES DW_USER(ID);
ALTER TABLE DW_USER_BET_DETAIL ADD CONSTRAINT FK_USER_BET FOREIGN KEY(USER_BET_ID) REFERENCES DW_USER_BET(ID);
