-- Nahrani produkcnich dat do datoveho skladu
INSERT INTO DW_MATCH (ID, TEAM1_NAME, TEAM2_NAME, DESCRIPTION, RESULT, PLAYED_AT)
SELECT M.ID, T1.NAME, T2.NAME, M.DESCRIPTION, M.RESULT, M.PLAYED_AT
FROM "Match" M
LEFT JOIN "Team" T1 ON M.TEAM1 = T1.ID
LEFT JOIN "Team" T2 ON M.TEAM2 = T2.ID;

INSERT INTO DW_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, BIRTHDATE, ADMIN)
SELECT U.ID, U.FIRST_NAME, U.LAST_NAME, U.EMAIL, U.PASSWORD, U.BIRTHDATE, U.ADMIN
FROM "User" U;

INSERT INTO DW_USER_BET (ID, BET_AMOUNT, RATE, CREATED_AT)
SELECT UB.ID, UB.BET_AMOUNT, B.RATE, UB.CREATED_AT
FROM "UserBet" UB
LEFT JOIN "Bet" B ON UB.BET_ID = B.ID;

INSERT INTO DW_USER_BET_DETAIL (MATCH_ID, USER_ID, USER_BET_ID)
SELECT M.ID, U.ID, UB.ID
FROM "UserBet" UB
LEFT JOIN "Bet" B ON UB.BET_ID = B.ID
LEFT JOIN "Match" M ON B.MATCH_ID = M.ID
LEFT JOIN "User" U ON UB.USER_ID = U.ID
