-- Smazání tabulek
DROP TABLE "Bet" CASCADE CONSTRAINTS;
DROP TABLE "Match" CASCADE CONSTRAINTS;
DROP TABLE "Team" CASCADE CONSTRAINTS;
DROP TABLE "User" CASCADE CONSTRAINTS;
DROP TABLE "UserAccount" CASCADE CONSTRAINTS;
DROP TABLE "UserBet" CASCADE CONSTRAINTS;

-- Smazání sekvencí
DROP SEQUENCE "SEQ_Bet_ID";
DROP SEQUENCE "SEQ_Match_ID";
DROP SEQUENCE "SEQ_Team_ID";
DROP SEQUENCE "SEQ_User_ID";
DROP SEQUENCE "SEQ_UserAccount_ID";
DROP SEQUENCE "SEQ_UserBet_ID";

-- Smazání procedur
DROP PROCEDURE "IS_ADULT";
DROP PROCEDURE "IS_BET_ENDING_DAY_BEFORE_MATCH";
DROP PROCEDURE "UPDATE_AVERAGE_BET_VALUE";

-- Smazání balíčku
DROP PACKAGE "BETTING_SHOP_MGMT";

-- Smazání tabulek datového skladu
DROP TABLE "DW_MATCH" CASCADE CONSTRAINTS;
DROP TABLE "DW_USER" CASCADE CONSTRAINTS;
DROP TABLE "DW_USER_BET" CASCADE CONSTRAINTS;
DROP TABLE "DW_USER_BET_DETAIL" CASCADE CONSTRAINTS;